#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RebuyFormsRating.Droid.Resource", IsApplication=false)]

namespace RebuyFormsRating.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030002
			public static int dark_gray = 2130903042;
			
			// aapt resource value: 0x7f030001
			public static int light_gray = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int teal = 2130903040;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public static int actionList = 2131034113;
			
			// aapt resource value: 0x7f050003
			public static int dialogButtonLeft = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int dialogButtonRight = 2131034116;
			
			// aapt resource value: 0x7f050008
			public static int feedbackDialogButtonCancel = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int feedbackDialogButtonSend = 2131034121;
			
			// aapt resource value: 0x7f050006
			public static int feedbackMessage = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int feedbackText = 2131034119;
			
			// aapt resource value: 0x7f050005
			public static int feedbackTitle = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public static int listView = 2131034122;
			
			// aapt resource value: 0x7f050000
			public static int message = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int qmessage = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public static int textItem = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int CustomActionSheet = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int CustomAlertSheet = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int CustomFeedbackSheet = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int CustomListView = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int TextViewItem = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int feedback = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
